apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kt7k1y0hz-java-quarkus
  janus-idp.io/tekton: kt7k1y0hz-java-quarkus
  backstage.io/kubernetes-id: kt7k1y0hz-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kt7k1y0hz-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
